import React, { useState, useEffect, useRef } from 'react';
import Head from 'next/head'
import Image from 'next/image'
//import { Inter } from 'next/font/google'
//import styles from '@/styles/Home.module.css'
//const inter = Inter({ subsets: ['latin'] })
import Footer from '../components/_App/Footer/Footer';
import Header from '@/components/_App/Header';
import BrandLogo from '@/components/_App/BrandLogo';
import FindLocation from '@/components/_App/FindLocation';
import Video from '@/components/_App/Video';
import TopHomePageBanner from '@/components/_App/TopHomePageBanner';
import PlanYourParty from '@/components/_App/PlanYourParty';
import RequestInfo from '@/components/_App/RequestInfo';
import GamesForEveryOne from '@/components/_App/GamesForEveryOne';
import GamesList from '@/components/_App/GamesList';
import GamesSlider from '@/components/_App/GamesSlider';
import 'react-responsive-modal/styles.css';
import { Modal } from 'react-responsive-modal';
import { useForm } from "react-hook-form";
import { yupResolver } from '@hookform/resolvers/yup'
import * as Yup from 'yup'


const modalSchema = Yup.object().shape({
  zipcode: Yup.number()
    .required('Zip code is a required field')// optional
    .typeError('Please enter valid zip code.')// optional as well
  // .test('len', 'Please enter valid zip code.', val => val.toString().length === 5)
})
const bg = {
  overlay: {
    background: "rgba(128, 128, 128, 0.5)"
  }
};

export default function Home() {
  // const zipCode = useRef(0)

  // let g2uZipCode = localStorage.getItem('g2u_zipcode'); // get zipcode from local storage

  // const [open, setOpen] = useState((g2uZipCode != null && g2uZipCode != 'undefined') ? false : true);
  // const onCloseModal = () => setOpen(false);
  // const [zipCodeServiceStaus, setZipCodeServiceStatus] = useState('')
  // const [isOpenTopChangeLocation, setIsOpenTopChangeLocation] = useState('');
  // const modalFormOptions = { resolver: yupResolver(modalSchema) }
  // const { register, setValue, formState: { errors, isSubmitting }, handleSubmit } = useForm(modalFormOptions);
  // const { register: register1, setValue: setValue1, formState: { errors: errors1, isSubmitting: isSubmitting1 }, handleSubmit: handleSubmit1 } = useForm(modalFormOptions); //for topbar change location


  //Games They'll Love Slider
  // useEffect(() => {
  //   console.log("call use effect **********************88")
  //   zipCode.current = g2uZipCode ? g2uZipCode : "00000"
  // }, [])


  // const apicallUrl = process.env.NEXT_PUBLIC_API_BASE_URL
  // const { data: gamesData, isLoading, isError, mutate } = SwrUtils(`${apicallUrl}/games/${zipCode.current}`)
  // console.log("swr data!!!!!!!", gamesData)
  // if (gamesData && gamesData.data?.games != null) {
  //   if (gamesData.data.games !== "" && gamesData.data.games.affiliate) {
  //     localStorage.setItem('g2u_zipcode', zipCode.current);
  //     open ? setOpen(false) : ''
  //     display ? '' : setDisplay(true)
  //   }
  // }

  // //Main popup submit handler
  // const onSubmit = async formValue => {
  //   const { zipcode } = formValue
  //   zipCode.current = zipcode
  //   mutate(`${apicallUrl}/games/${zipCode.current}`)
  // }

  // //topbar change location submit handler
  // const onSubmitTopBarChangeLocation = async formValue => {
  //   const { zipcode } = formValue

  // };
  // if (errors1?.zipcode != null) {
  //   setValue1('zipcode', '')
  //   console.log("errrrTopBar", errors1)
  // }

  // if (errors?.zipcode != null) {
  //   setValue('zipcode', '')
  //   console.log("errrr", errors)
  // }


  return (
    <>
      <Head>
        <title>Austin Game Trucks, Laser Tag & Hamster Balls from Games2U</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/assets/favicon-16x16.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/assets/favicon-32x32.png" />
        <link rel="shortcut icon" href="/assets/favicon-16x16.png" />
      </Head>

      {/* /.modal box*/}

      {/* <ZipCodePopup /> */}



      {/* /.modal box*/}
      < div className="container-fluid" >
        {/* ----------- Header section start with mobile naviagtion --------  */}
        < Header
        // categoryData={gamesData?.data.games.categories}
        // affiliate={gamesData?.data.games.affiliate}
        // register={register1}
        // handleSubmit={handleSubmit1}
        // errors={errors1}
        // onSubmitTopBarChangeLocation={onSubmitTopBarChangeLocation}
        // isOpen={isOpenTopChangeLocation}
        />
        {/* ----------- End Header section start with mobile naviagtion ------ */}

        {/* ----------- Start section for Video, Find a Location and Brand Logo ------ */}
        <div className="row no-padding " id="headerBanner">
          <div className="ti-page-header row clearfix">
            <Video />
            <FindLocation />
            <BrandLogo />
          </div>
        </div>
        {/* ----------- End section for Video, Find a Location and Brand Logo --------- */}
      </div >
      <div className="container-fluid">
        <TopHomePageBanner />

        <GamesForEveryOne />

        <div className="row ti-orange-background no-margin no-padding" id="gamesTheyLove">
          <div className="col-xs-12 no-padding">
            <div className="ti-orange-background clearfix">
              <div className="col-sm-12 no-padding">
                <h2 className="limited-width">Games They'll Love!</h2>
                <div className="row ti-row no-side-padding no-side-margin remove-overflow">
                  <div className="ti-slider-parents">
                    <GamesSlider />
                  </div>
                </div>
                <GamesList />
              </div>
            </div>
          </div>
        </div>



        <RequestInfo
          content="Ready to host the event they'll never forget?"
          classNameStyle="ti-dark-orange-background"
        />

        <PlanYourParty />

        <RequestInfo
          content="Book Today and be the Hero of Your Next Event!"
          classNameStyle="ti-blue-gradient-background"
        />
      </div>

      {/* <Footer /> */}

    </>
  )
}
